# Generated by Django 3.1.6 on 2021-03-17 16:40

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210315_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_user',
            field=models.ImageField(default='/static_cdn/media_root/user/104631-200.png', upload_to=account.models.upload_user_photo),
        ),
    ]
