# Generated by Django 3.1.6 on 2021-03-17 16:42

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210317_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_user',
            field=models.ImageField(default='/media/User/None--maryam.jpg', upload_to=account.models.upload_user_photo),
        ),
    ]
