# Generated by Django 3.1.6 on 2021-03-17 16:44

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210317_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_user',
            field=models.ImageField(default='User/104631-200.png', upload_to=account.models.upload_user_photo),
        ),
    ]
