# Generated by Django 3.1.6 on 2021-02-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Music', max_length=150)),
                ('release_date', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MusicDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Album.album')),
                ('musicdetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Music.music')),
            ],
        ),
    ]
