# Generated by Django 3.1.6 on 2021-02-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicdetail',
            old_name='musicdetail',
            new_name='musicname',
        ),
    ]
