# Generated by Django 3.1.6 on 2021-02-09 14:12

import Music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_auto_20210209_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Music.models.upload_image),
        ),
    ]
