# Generated by Django 3.1.6 on 2021-02-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Genre', '0001_initial'),
        ('Music', '0003_music_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdetail',
            name='Genredetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Genre.genre'),
        ),
    ]
