# Generated by Django 3.1.6 on 2021-02-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_musicdetail_artistdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='length',
            field=models.CharField(default='00', max_length=150),
        ),
    ]
