# Generated by Django 3.1.6 on 2021-02-14 08:41

import Music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_music_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='SongFile',
            field=models.FileField(blank=True, null=True, upload_to=Music.models.upload_file),
        ),
    ]
