# Generated by Django 3.1.6 on 2021-02-27 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_music_songfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 17, 27, 59, 869964)),
        ),
    ]
