# Generated by Django 3.1.6 on 2021-02-27 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0009_auto_20210227_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 19, 20, 16, 886530)),
        ),
    ]
