# Generated by Django 3.1.6 on 2021-02-28 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0010_auto_20210227_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 19, 19, 12, 621975)),
        ),
    ]
