# Generated by Django 3.1.6 on 2021-03-02 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0017_auto_20210302_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 16, 39, 54, 315264)),
        ),
    ]
