# Generated by Django 3.1.6 on 2021-03-03 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0025_auto_20210302_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 18, 54, 55, 686474)),
        ),
    ]
