# Generated by Django 3.1.6 on 2021-03-03 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0026_auto_20210303_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 18, 55, 55, 183081)),
        ),
    ]
