# Generated by Django 3.1.6 on 2021-03-04 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0027_auto_20210303_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 19, 21, 40, 312821)),
        ),
    ]
