# Generated by Django 3.1.6 on 2021-03-04 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0028_auto_20210304_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 19, 24, 33, 544108)),
        ),
    ]
