# Generated by Django 3.1.6 on 2021-03-06 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0031_auto_20210304_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 20, 22, 46, 177401)),
        ),
    ]
