# Generated by Django 3.1.6 on 2021-03-06 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0032_auto_20210306_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 20, 24, 6, 37178)),
        ),
    ]
