# Generated by Django 3.1.6 on 2021-03-09 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0038_auto_20210307_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='PriceMusic',
            field=models.CharField(default=100, max_length=150),
        ),
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 11, 24, 35, 752519)),
        ),
    ]
