# Generated by Django 3.1.6 on 2021-03-15 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0048_auto_20210315_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 22, 4, 4, 869543)),
        ),
    ]
