# Generated by Django 3.1.6 on 2021-03-16 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0052_auto_20210316_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 22, 34, 0, 863428)),
        ),
    ]
