# Generated by Django 3.1.6 on 2021-03-17 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0054_auto_20210317_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 20, 10, 24, 956553)),
        ),
    ]
