# Generated by Django 3.1.6 on 2021-03-17 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0055_auto_20210317_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 20, 12, 13, 803302)),
        ),
    ]
