# Generated by Django 3.1.6 on 2021-03-02 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_comments', models.DateTimeField(default=datetime.datetime(2021, 3, 2, 11, 45, 10, 651240))),
                ('descriptions', models.TextField(max_length=500)),
            ],
        ),
    ]
