# Generated by Django 3.1.6 on 2021-03-02 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210302_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time_comments',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 11, 51, 31, 332554)),
        ),
    ]
