# Generated by Django 3.1.6 on 2021-03-02 08:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20210302_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='time_comments',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 12, 0, 52, 618668)),
        ),
        migrations.AlterField(
            model_name='user_comments',
            name='user_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comments.subscriber'),
        ),
    ]
