# Generated by Django 3.1.6 on 2021-03-02 13:09

import comments.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20210302_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='image',
            field=models.ImageField(null=True, upload_to=comments.models.uploadimage),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time_comments',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 16, 39, 54, 331962)),
        ),
    ]
