# Generated by Django 3.1.6 on 2021-03-02 13:48

import comments.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_auto_20210302_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time_comments',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 17, 18, 55, 393253)),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=comments.models.uploadimage),
        ),
    ]
