# Generated by Django 3.1.6 on 2021-03-04 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0018_auto_20210304_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time_comments',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 19, 38, 19, 19701)),
        ),
    ]
