# Generated by Django 3.1.6 on 2021-03-06 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0020_auto_20210304_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('descriptionblog', models.TextField(max_length=500)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 3, 6, 20, 22, 46, 190851))),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='time_comments',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 20, 22, 46, 190851)),
        ),
        migrations.AddField(
            model_name='user_comments',
            name='blog_comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comments.blogs'),
        ),
    ]
