# Generated by Django 3.1.6 on 2021-03-06 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0021_auto_20210306_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='descriptionblog',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 20, 24, 6, 37178)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time_comments',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 20, 24, 6, 37178)),
        ),
    ]
