# Generated by Django 3.1.6 on 2021-03-06 17:34

import comments.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0022_auto_20210306_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(null=True, upload_to=comments.models.upload_image_blog),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 21, 4, 5, 536421)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time_comments',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 21, 4, 5, 536421)),
        ),
    ]
