# Generated by Django 3.1.6 on 2021-03-07 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0024_auto_20210307_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 18, 44, 32, 844750)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time_comments',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 18, 44, 32, 844750)),
        ),
    ]
