# Generated by Django 3.1.6 on 2021-03-07 14:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Music', '0035_auto_20210307_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 3, 7, 18, 12, 59, 452347))),
                ('is_paid', models.BooleanField(default=False)),
                ('user_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseUserMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Music_Purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Music.musicdetail')),
                ('Purchase_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.purchaseuser')),
            ],
        ),
    ]
