# Generated by Django 3.1.6 on 2021-03-07 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0036_auto_20210307_1844'),
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 18, 44, 32, 847693)),
        ),
        migrations.AlterField(
            model_name='purchaseusermusic',
            name='Music_Purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Music.music'),
        ),
    ]
