# Generated by Django 3.1.6 on 2021-03-07 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0003_auto_20210307_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseusermusic',
            name='is_paid_music',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 22, 57, 13, 51612)),
        ),
    ]
