# Generated by Django 3.1.6 on 2021-03-10 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0005_auto_20210309_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 11, 31, 7, 475178)),
        ),
    ]
