# Generated by Django 3.1.6 on 2021-03-14 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0008_auto_20210314_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 19, 27, 55, 761689)),
        ),
    ]
