# Generated by Django 3.1.6 on 2021-03-15 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0009_auto_20210314_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 20, 2, 52, 182043)),
        ),
    ]
