# Generated by Django 3.1.6 on 2021-03-15 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0010_auto_20210315_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 20, 7, 29, 512730)),
        ),
    ]
