# Generated by Django 3.1.6 on 2021-03-16 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0016_auto_20210315_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 20, 21, 41, 767323)),
        ),
    ]
