# Generated by Django 3.1.6 on 2021-03-17 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0023_auto_20210317_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 20, 14, 50, 605552)),
        ),
    ]
