# Generated by Django 3.1.6 on 2021-02-14 17:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_music_songfile'),
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadsong',
            name='Download_Time',
            field=models.TimeField(default=datetime.time(21, 18, 5, 423564)),
        ),
        migrations.CreateModel(
            name='DownloadDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriceDownload', models.CharField(max_length=150)),
                ('Download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.downloadsong')),
                ('MusicDownload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Music.music')),
            ],
        ),
    ]
