# Generated by Django 3.1.6 on 2021-02-15 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20210214_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaddetail',
            name='PriceDownload',
            field=models.CharField(default=100, max_length=150),
        ),
        migrations.AlterField(
            model_name='downloadsong',
            name='Download_Time',
            field=models.TimeField(default=datetime.time(12, 26, 21, 603584)),
        ),
    ]
