# Generated by Django 3.1.6 on 2021-02-15 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_auto_20210215_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadsong',
            name='Download_Time',
            field=models.TimeField(default=datetime.time(12, 28, 54, 725458)),
        ),
    ]
