# Generated by Django 3.1.6 on 2021-02-16 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_auto_20210215_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaddetail',
            name='recnetlydownload',
            field=models.TimeField(default=datetime.time(18, 45, 47, 686944)),
        ),
        migrations.AlterField(
            model_name='downloadsong',
            name='Download_Time',
            field=models.TimeField(default=datetime.time(18, 45, 47, 686944)),
        ),
    ]
