# Generated by Django 3.1.6 on 2021-03-03 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0037_auto_20210303_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaddetail',
            name='recnetlydownload',
            field=models.TimeField(default=datetime.time(18, 55, 55, 183081)),
        ),
        migrations.AlterField(
            model_name='downloadsong',
            name='Download_Time',
            field=models.TimeField(default=datetime.time(18, 55, 55, 183081)),
        ),
    ]
