# Generated by Django 3.1.6 on 2021-03-04 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0041_auto_20210304_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaddetail',
            name='recnetlydownload',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 19, 58, 20, 901199)),
        ),
        migrations.AlterField(
            model_name='downloadsong',
            name='Download_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 19, 58, 20, 901199)),
        ),
    ]
