# Generated by Django 3.1.6 on 2021-03-06 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0042_auto_20210304_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaddetail',
            name='recnetlydownload',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 20, 22, 46, 177401)),
        ),
        migrations.AlterField(
            model_name='downloadsong',
            name='Download_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 20, 22, 46, 177401)),
        ),
    ]
