# Generated by Django 3.1.6 on 2021-03-06 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0044_auto_20210306_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaddetail',
            name='recnetlydownload',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 21, 4, 5, 528442)),
        ),
        migrations.AlterField(
            model_name='downloadsong',
            name='Download_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 21, 4, 5, 528442)),
        ),
    ]
