# Generated by Django 3.1.6 on 2021-03-07 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0045_auto_20210306_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaddetail',
            name='recnetlydownload',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 18, 12, 59, 441192)),
        ),
        migrations.AlterField(
            model_name='downloadsong',
            name='Download_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 18, 12, 59, 441192)),
        ),
    ]
