# Generated by Django 3.1.6 on 2021-03-15 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0054_auto_20210314_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaddetail',
            name='recnetlydownload',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 20, 2, 52, 172021)),
        ),
        migrations.AlterField(
            model_name='downloadsong',
            name='Download_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 20, 2, 52, 172021)),
        ),
    ]
