# Generated by Django 3.1.6 on 2021-03-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20210315_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_by_user', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FromUser', to='account.userprofile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ToUSer', to='account.userprofile')),
            ],
        ),
    ]
