# Generated by Django 3.1.6 on 2021-03-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210315_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='accept_by_user',
            field=models.CharField(default='False', max_length=50),
        ),
    ]
