# Generated by Django 3.1.6 on 2021-03-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210316_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='equal_follow',
            field=models.BooleanField(default=False),
        ),
    ]
