# Generated by Django 3.1.6 on 2021-03-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_followers_equal_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='equal_follow',
        ),
    ]
