# Generated by Django 3.1.6 on 2021-03-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tite', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
