# Generated by Django 3.1.6 on 2021-03-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_settings',
            old_name='tite',
            new_name='title',
        ),
    ]
