# Generated by Django 3.1.6 on 2021-02-16 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0002_auto_20210215_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(18, 45, 47, 686944)),
        ),
    ]
