# Generated by Django 3.1.6 on 2021-02-20 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0003_auto_20210216_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(12, 48, 29, 28245)),
        ),
    ]
