# Generated by Django 3.1.6 on 2021-02-21 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0004_auto_20210220_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(12, 37, 24, 468953)),
        ),
    ]
