# Generated by Django 3.1.6 on 2021-02-21 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0005_auto_20210221_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(13, 29, 14, 602249)),
        ),
    ]
