# Generated by Django 3.1.6 on 2021-02-23 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0008_auto_20210223_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(13, 16, 56, 296717)),
        ),
    ]
