# Generated by Django 3.1.6 on 2021-02-23 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0009_auto_20210223_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(13, 20, 18, 259787)),
        ),
    ]
