# Generated by Django 3.1.6 on 2021-02-23 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0010_auto_20210223_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(21, 50, 9, 554821)),
        ),
    ]
