# Generated by Django 3.1.6 on 2021-02-23 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0011_auto_20210223_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(22, 5, 1, 260027)),
        ),
    ]
