# Generated by Django 3.1.6 on 2021-02-23 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0013_auto_20210223_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(22, 40, 14, 558146)),
        ),
    ]
