# Generated by Django 3.1.6 on 2021-02-24 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0015_auto_20210223_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(13, 6, 44, 641288)),
        ),
    ]
