# Generated by Django 3.1.6 on 2021-02-27 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0016_auto_20210224_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(17, 27, 59, 873005)),
        ),
    ]
