# Generated by Django 3.1.6 on 2021-02-27 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0018_auto_20210227_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(19, 20, 16, 889451)),
        ),
    ]
