# Generated by Django 3.1.6 on 2021-02-28 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0019_auto_20210227_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(19, 19, 12, 621975)),
        ),
    ]
