# Generated by Django 3.1.6 on 2021-03-02 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0020_auto_20210228_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(11, 45, 10, 651240)),
        ),
    ]
