# Generated by Django 3.1.6 on 2021-03-02 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0023_auto_20210302_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(12, 0, 52, 618668)),
        ),
    ]
