# Generated by Django 3.1.6 on 2021-03-02 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0024_auto_20210302_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(12, 1, 17, 192208)),
        ),
    ]
