# Generated by Django 3.1.6 on 2021-03-02 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0025_auto_20210302_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(12, 35, 20, 383623)),
        ),
    ]
