# Generated by Django 3.1.6 on 2021-03-02 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0026_auto_20210302_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(16, 39, 54, 331962)),
        ),
    ]
