# Generated by Django 3.1.6 on 2021-03-02 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0028_auto_20210302_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(17, 14, 14, 183004)),
        ),
    ]
