# Generated by Django 3.1.6 on 2021-03-02 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0033_auto_20210302_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(22, 39, 27, 488428)),
        ),
    ]
