# Generated by Django 3.1.6 on 2021-03-03 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0034_auto_20210302_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(18, 54, 55, 686474)),
        ),
    ]
