# Generated by Django 3.1.6 on 2021-03-03 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0035_auto_20210303_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(18, 55, 55, 183081)),
        ),
    ]
