# Generated by Django 3.1.6 on 2021-03-04 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0036_auto_20210303_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(19, 21, 40, 314740)),
        ),
    ]
