# Generated by Django 3.1.6 on 2021-03-04 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0037_auto_20210304_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(19, 24, 33, 545104)),
        ),
    ]
