# Generated by Django 3.1.6 on 2021-03-04 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0038_auto_20210304_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.TimeField(default=datetime.time(19, 38, 19, 15711)),
        ),
    ]
