# Generated by Django 3.1.6 on 2021-03-04 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0039_auto_20210304_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.DateTimeField(default=datetime.time(19, 58, 20, 904189)),
        ),
    ]
