# Generated by Django 3.1.6 on 2021-03-06 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0040_auto_20210304_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.DateTimeField(default=datetime.time(20, 22, 46, 177401)),
        ),
    ]
