# Generated by Django 3.1.6 on 2021-03-06 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0041_auto_20210306_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.DateTimeField(default=datetime.time(20, 24, 6, 37178)),
        ),
    ]
