# Generated by Django 3.1.6 on 2021-03-07 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0045_auto_20210307_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.DateTimeField(default=datetime.time(20, 0, 12, 154271)),
        ),
    ]
