# Generated by Django 3.1.6 on 2021-03-07 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0046_auto_20210307_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.DateTimeField(default=datetime.time(22, 57, 13, 44572)),
        ),
    ]
