# Generated by Django 3.1.6 on 2021-03-09 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0047_auto_20210307_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.DateTimeField(default=datetime.time(11, 24, 35, 754513)),
        ),
    ]
