# Generated by Django 3.1.6 on 2021-03-14 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0049_auto_20210310_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 17, 18, 10, 18403)),
        ),
    ]
