# Generated by Django 3.1.6 on 2021-03-15 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0055_auto_20210315_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 21, 10, 10, 595393)),
        ),
    ]
