# Generated by Django 3.1.6 on 2021-03-15 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0058_auto_20210315_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 22, 6, 55, 170039)),
        ),
    ]
