# Generated by Django 3.1.6 on 2021-03-16 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorit', '0060_auto_20210316_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritmusic',
            name='TimeFavorti',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 21, 37, 24, 107015)),
        ),
    ]
