# Generated by Django 3.1.6 on 2021-02-21 09:07

import UserPlayList.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongFile', models.FileField(blank=True, null=True, upload_to=UserPlayList.models.upload_song_user)),
                ('SongName', models.CharField(max_length=150)),
                ('ArtistName', models.CharField(max_length=150)),
                ('AlbumName', models.CharField(max_length=150)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayListDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayListSelect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserPlayList.add_playlist')),
                ('UserPlayList', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
