# Generated by Django 3.1.6 on 2021-02-23 08:48

import UserPlayList.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPlayList', '0002_add_playlist_playlistname'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_playlist',
            name='PlayListImage',
            field=models.ImageField(blank=True, null=True, upload_to=UserPlayList.models.upload_image_playlist),
        ),
    ]
