# Generated by Django 3.1.6 on 2021-02-23 09:46

import UserPlayList.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserPlayList', '0003_add_playlist_playlistimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongFile', models.FileField(blank=True, null=True, upload_to=UserPlayList.models.upload_song_user)),
            ],
        ),
        migrations.RemoveField(
            model_name='add_playlist',
            name='SongFile',
        ),
        migrations.AddField(
            model_name='add_playlist',
            name='Music_File',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserPlayList.musicfile'),
        ),
    ]
