# Generated by Django 3.1.6 on 2021-02-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPlayList', '0004_auto_20210223_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_playlist',
            name='AlbumName',
        ),
        migrations.RemoveField(
            model_name='add_playlist',
            name='ArtistName',
        ),
        migrations.RemoveField(
            model_name='add_playlist',
            name='SongName',
        ),
        migrations.AddField(
            model_name='musicfile',
            name='AlbumName',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='musicfile',
            name='ArtistName',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='musicfile',
            name='SongName',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
