# Generated by Django 3.1.6 on 2021-02-24 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserPlayList', '0005_auto_20210223_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_playlist',
            name='Music_File',
        ),
        migrations.AddField(
            model_name='playlistdetail',
            name='Music_File',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='UserPlayList.musicfile'),
        ),
    ]
