# Generated by Django 3.1.6 on 2021-03-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPlayList', '0006_auto_20210224_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
