# Generated by Django 3.1.6 on 2021-03-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPlayList', '0007_musicfile_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfile',
            name='is_favorit',
            field=models.BooleanField(default=False),
        ),
    ]
