# Generated by Django 3.1.6 on 2021-02-09 14:21

import Artist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtistName', models.CharField(default='Artist', max_length=150)),
                ('ImageArtsit', models.ImageField(upload_to=Artist.models.uploadimage)),
            ],
        ),
    ]
