# Generated by Django 3.1.6 on 2021-02-27 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Music', '0010_auto_20210227_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryByuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('History_Song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Music.musicdetail')),
                ('History_User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
